tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "lokalise/cli-2"
brew "ruby"
brew "cocoapods"
brew "mas"
brew "mint"
brew "node"
brew "pyenv"
brew "rustup-init"
brew "starship"
brew "stow"
brew "swiftformat"
brew "swiftlint"
brew "lokalise/cli-2/lokalise2"
cask "adobe-creative-cloud"
cask "android-file-transfer"
cask "blender"
cask "brave-browser"
cask "cleanmymac"
cask "deepl"
cask "dropbox"
cask "figma"
cask "firefox"
cask "flutter"
cask "gltfquicklook"
cask "google-chrome"
cask "insomnia"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "min"
cask "notion"
cask "pop"
cask "raycast"
cask "signal"
cask "slack"
cask "spotify"
cask "todoist"
cask "twist"
cask "visual-studio-code"
cask "warp"
cask "xcodes"
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "DaisyDisk", id: 411643860
mas "Disk Speed Test", id: 425264550
mas "Final Cut Pro", id: 424389933
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Surfshark", id: 1437809329
mas "Xcode", id: 497799835
